name: Node.js CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths-ignore:
      - './.github/*'
      - './.vscode/*'
      - './public/*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run "lint:check"
      - run: npm run test
